apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: demo-voting-app
spec:
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004
  type: NodePort
